[build]
  command = "gatsby build"
  publish = "public/"
  image = "noble"

[build.environment]
  NODE_VERSION = "22"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true
  ignore_html_forms = true

[[build.branch]]
  pattern = "master"
